### PR TITLE
Update authors/organizers

### LINKED ISSUE #11: Updates
- [x] Location is set to Mila
- [x] Add application form
- [x] Add application deadline
- [x] Change language from registration to application
- [x] List of organizers

I will create a PR.

### PR DESCRIPTION
**Pull request by rly**
Fix #11.

- Add option to share on bluesky
- Remove unnecessary archives page?
- Update schedule
- Update FAQ language
- Add application form, location, and more info
- Add organizers list (abc order)

### CODE REVIEW

**Comment by rly** [comment]
I haven't built this locally but I hope I did not break any formatting...

**Comment by bimac** [comment]
Thanks Ryan, all looks fine - I'll go ahead and merge.

**Comment by bimac** [comment]
Re: archive. The initial idea was to make it a bit more blog-like. I.e., we could have brief update posts (registrations opened / closed, one week to go, project presentations etc). That's were the archive might become handy. But not sure if its worth it ...

**Comment by rly** [comment]
Oh, I see. I like that idea, but I think we could just the homepage post listing for that unless we might have too many posts.

**Pull request merged**
